### PR TITLE
Remove expiring Lockheed Martin cert

### PR DESCRIPTION
**Pull request by matthinz**
Cert expires after 2024-04-30.

## 🛠 Summary of changes

Removes a cert that is set to expire on April 30th. I can find [no evidence](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-2419200~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20strcontains*28*40message*2c*20*275D*3aBD*3a71*3a27*3a1D*3a66*3aC2*3a86*3aDD*3a05*3aBA*3a17*3a49*3a0B*3a4D*3a83*3a90*3a3E*3a98*3a9E*27*29*20or*20strcontains*28*40message*2c*20*2701*3ac8*3a1f*3aaa*3aab*3a4e*3ac1*3a89*3a26*3a2b*3a15*3a97*3a65*3a66*3a5b*3a07*27*29*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2010~queryId~'a4fd203dbe018fa-c2a07066-4f6ef5d-873bad1-c04379409dd14772f4567d3d~source~(~'prod_*2fsrv*2fpki-rails*2fshared*2flog*2fproduction.log))) of it being used in prod in the last 4 weeks.

### CODE REVIEW

**Comment by aduth** [comment]
We have a tracking ticket for this ([LG-12998](https://cm-jira.usa.gov/browse/LG-12998)), which is/was expecting a replacement to become available due to a notification on [FPKI Notifications](https://www.idmanagement.gov/fpki/notifications/#notifications):

>CertiPath intends to issue a new cross certificate to Lockheed Martin Root CA 6 on or about April 16, 2024.

Though we're getting awfully close to the deadline and I haven't seen any replacement yet. Still, I think we typically wait until after the actual expiration to remove the certificate ([related docs](https://handbook.login.gov/articles/troubleshooting-expiring-pivcac.html#handling-expiring-certificates-when-no-replacements-exist)). We could use this pull request at that point.

**Comment by aduth** [comment]
Will need to regenerate the bundles. I expect build will fail accordingly.

**Comment by matthinz** [comment]
Ah, gotcha. I will close this and let y'all take it.

**Comment by aduth** [comment]
Follow-up at #451

**Pull request closed without merging**
