### PR TITLE
Add FPKI G2 certificate per https://fpki.idmanagement.gov/common/

### PR DESCRIPTION
**Pull request by sharms**
In order to support certificate signed by the new FPKI G2 certificate, the application should check the chain of trust and validate it using the new certificate.

I am unaware of what the testing process is to determine if this change is successful, or other dependent configurations and would welcome any help!

### CODE REVIEW

**Comment by amoose** [comment]
And can we add a spec to validate the new root CA?

**Review by mitchellhenke — APPROVED** [review]

**Comment by zachmargolis** [comment]
Pushed a commit to sync this with the `main` branch, it had diverged

**Comment by amathews-fs** [comment]
Are we good to go ahead and merge this?

**Comment by zachmargolis** [comment]
Based on [Slack discussion](https://gsa-tts.slack.com/archives/C0NGESUN5/p1618590362072700), yes, so I'll merge

**Pull request merged**
