### PR TITLE
LG-175: Dockerize for development

### PR DESCRIPTION
**Pull request by zachmargolis**
I basically copy-pasted what Clint did in IDP to do this

To make sure it works, I ran the rest suite:

```
docker-compose exec web bundle exec rspec
```

I got the server to locally work with my PIV with PKI inside the docker container, but the IDP was **outside** the container ☹️ 

- The IDP backend makes a POST to the PKI backend, and that failed when IDP was inside a Docker container, so I think we need to poke a hole in the IDP container at 8443 so it can get to the PKI Docker container? That's beyond my expertise (and outside this repo) so I consider this good enough for now?

Would love to hear from others who give this a shot!

### CODE REVIEW

**Comment by ctro** [comment]
This looks great so far!  I'll pull it down and see if I can get it to build / run.

A thing I'm thinking is that _both_  IDP and this use `postgres` and `redis` in their clusters.  It would be great to only run those once -- _without_ having everything in the same compose file 🤔 .  

Also, we can def poke a port/hole in some other container for POSTS, etc.

**Comment by ctro** [comment]
🇺🇸 👍 Looks great and works for me too.

**Comment by ctro** [comment]
Well, one small improvement:  create the test database as part of the setup script:
https://github.com/18F/identity-pki/pull/115

**Comment by zachmargolis** [comment]
Thanks @ctro for reviewing and your PR!

**Pull request merged**
